server:
  port: 8111

spring:
  profiles:
    active:
      - mp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.22.129.38:6033/security?useSSL=false
    username: root
    password: 123@abcd

